### ISSUE TITLE
Configuration options for html-minifier

### ISSUE THREAD

**Issue by ferretwithaberet** [chenjuneking/rollup-plugin-bundle-inject#1]
Please expose the configuration options of the `html-minifier` package used under the hood. Also, there should be an option to avoid minification altogether.

I was wondering today why the `<path>` element inside of an `<svg>` was getting removed after the build was done. It seems that the `removeEmptyElements` setting is doing that.

If I will have time I will contribute this myself.

**Comment by chenjuneking** [comment]
Thanks your PR, it's really nice! @ferretwithaberet
